In [15]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

Question 1: What version of Pandas did you install?

In [16]:
pd.__version__

'2.2.3'

Question 2: How many records are in the dataset?

In [18]:
df.shape[0]

9704

Question 3: How many fuel types are presented in the dataset?

In [19]:
df["fuel_type"].nunique()

2

Question 4: How many columns in the dataset have missing values?

In [27]:
(df.isna().sum() > 0).sum()

np.int64(4)

Question 5: What's the maximum fuel efficiency of cars from Asia?

In [40]:
round(df.loc[df["origin"] == "Asia", "fuel_efficiency_mpg"].max(), 2)

23.76

Question 6 :
- Find the median value of the horsepower column in the dataset.
- Next, calculate the most frequent value of the same horsepower column.
- Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
- Now, calculate the median value of horsepower once again.

In [44]:
df['horsepower'].median()

149.0

In [51]:
max = df['horsepower'].value_counts().idxmax()
max

np.float64(152.0)

In [55]:
df['horsepower'] = df['horsepower'].fillna(max)
df['horsepower']

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [56]:
df['horsepower'].median()

152.0

Question 6:
- Select all the cars from Asia
- Select only columns vehicle_weight and model_year
- Select the first 7 values
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?

In [63]:
df_asia = df[df['origin'] =="Asia"]
df_asia = df_asia.reset_index(drop=True)
df_asia.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
1,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
2,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
3,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
4,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730

In [70]:
X = df_asia.loc[0:6,['vehicle_weight',"model_year"]].values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [72]:
XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [73]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [77]:
w = XTX_inv.dot(X.T).dot(y)

In [80]:
w.sum().round(3)

np.float64(0.519)